services:
  db:
    image: mariadb:11.2
    environment:
      MARIADB_ROOT_PASSWORD: foo
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8881:8080

volumes:
  data: